name: UnnecessaryTTL | Sync sapo orders
on:
  workflow_dispatch:
    inputs:
      repo_ref:
        description: Remote ref
        required: false
        default: "main"

      auto_re_trigger:
        description: Auto re-trigger?
        required: false
        default: "true"

      skip_completed_orders:
        description: Skip completed or canceled orders?
        required: false
        default: "false"

  repository_dispatch:
    types:
      - webhook
      - auto_re_trigger_ttl

  schedule:
    - cron: "0 */2 * * *"

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  sync-orders:
    name: Sync orders
    runs-on: macos-latest
    timeout-minutes: 360
    env:
      REPO_REF: ${{ github.event.inputs.repo_ref || 'main' }}
      AUTO_RE_TRIGGER: ${{ github.event.inputs.auto_re_trigger || 'true' }}
      SKIP_COMPLETED_ORDERS: ${{ github.event.inputs.skip_completed_orders || 'false' }}

    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Ho_Chi_Minh"
          timezoneMacos: "Asia/Ho_Chi_Minh"
          timezoneWindows: "Singapore Standard Time"
      - uses: actions/checkout@v2
        with:
          repository: "withDustin/unnecessary-data-hub"
          token: ${{ secrets.DUONGDEV_GH_TOKEN }}
          ref: ${{ env.REPO_REF }}

      - uses: actions/setup-node@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --production=false

      - name: Run
        run: WS=ttl yarn start:sapo

      # - name: Sleep for 5 minutes
      #   uses: jakejarvis/wait-action@master
      #   if: env.AUTO_RE_TRIGGER == 'true'
      #   with:
      #     time: "5m"

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        if: env.AUTO_RE_TRIGGER == 'true' || failure()
        with:
          token: ${{ secrets.DUONGDEV_GH_TOKEN }}
          event-type: auto_re_trigger_ttl
          client-payload: '{"repo_ref": "${{ github.event.inputs.repo_ref }}", "auto_re_trigger": "${{ github.event.inputs.auto_re_trigger }}", "skip_completed_orders": "${{ github.event.inputs.skip_completed_orders }}"}'
